// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package sqlc

import (
	"context"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (name, user_id, created_at, updated_at)
VALUES ($1, $2, now(), now())
RETURNING id, name, user_id, created_at, updated_at
`

type CreateBoardParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Name, arg.UserID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserBoardByID = `-- name: DeleteUserBoardByID :exec
DELETE FROM boards
WHERE id = $1 AND user_id = $2
`

type DeleteUserBoardByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteUserBoardByID(ctx context.Context, arg DeleteUserBoardByIDParams) error {
	_, err := q.db.Exec(ctx, deleteUserBoardByID, arg.ID, arg.UserID)
	return err
}

const getUserBoardByID = `-- name: GetUserBoardByID :one
SELECT id, name, user_id, created_at, updated_at
FROM boards
WHERE id = $1 AND user_id = $2
`

type GetUserBoardByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetUserBoardByID(ctx context.Context, arg GetUserBoardByIDParams) (Board, error) {
	row := q.db.QueryRow(ctx, getUserBoardByID, arg.ID, arg.UserID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBoards = `-- name: GetUserBoards :many
SELECT id, name, user_id, created_at, updated_at
FROM boards
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserBoards(ctx context.Context, userID string) ([]Board, error) {
	rows, err := q.db.Query(ctx, getUserBoards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserBoardByID = `-- name: UpdateUserBoardByID :one
UPDATE boards
SET name = $1, updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, name, user_id, created_at, updated_at
`

type UpdateUserBoardByIDParams struct {
	Name   string `json:"name"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateUserBoardByID(ctx context.Context, arg UpdateUserBoardByIDParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateUserBoardByID, arg.Name, arg.ID, arg.UserID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
