// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package sqlc

import (
	"context"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (name, user_id, created_at, updated_at)
VALUES ($1, $2, now(), now())
RETURNING id, name, user_id, created_at, updated_at
`

type CreateBoardParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Name, arg.UserID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
