// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (list_id, title, description, status, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, list_id, position, title, description, status, created_at, updated_at
`

type CreateCardParams struct {
	ListID      string      `json:"list_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Position    int32       `json:"position"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ListID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Position,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Position,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListCards = `-- name: GetListCards :many
SELECT id, list_id, position, title, description, status, created_at, updated_at
FROM cards
WHERE list_id = $1
ORDER BY position ASC
`

func (q *Queries) GetListCards(ctx context.Context, listID string) ([]Card, error) {
	rows, err := q.db.Query(ctx, getListCards, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Position,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
