// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lists.sql

package sqlc

import (
	"context"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (name, board_id, position)
VALUES ($1, $2, $3)
RETURNING id, name, board_id, position, created_at, updated_at
`

type CreateListParams struct {
	Name     string `json:"name"`
	BoardID  string `json:"board_id"`
	Position int32  `json:"position"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.Name, arg.BoardID, arg.Position)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BoardID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
