// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lists.sql

package sqlc

import (
	"context"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (name, board_id, position)
VALUES ($1, $2, $3)
RETURNING id, name, board_id, position, created_at, updated_at
`

type CreateListParams struct {
	Name     string `json:"name"`
	BoardID  string `json:"board_id"`
	Position int32  `json:"position"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.Name, arg.BoardID, arg.Position)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BoardID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM lists
WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteList, id)
	return err
}

const getBoardLists = `-- name: GetBoardLists :many
SELECT id, name, board_id, position, created_at, updated_at
FROM lists
WHERE board_id = $1
ORDER BY position ASC
`

func (q *Queries) GetBoardLists(ctx context.Context, boardID string) ([]List, error) {
	rows, err := q.db.Query(ctx, getBoardLists, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoardID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getList = `-- name: GetList :one
SELECT id, name, board_id, position, created_at, updated_at
FROM lists
WHERE id = $1
`

func (q *Queries) GetList(ctx context.Context, id string) (List, error) {
	row := q.db.QueryRow(ctx, getList, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BoardID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserListByID = `-- name: GetUserListByID :one
SELECT lists.id, lists.name, lists.board_id, lists.position, lists.created_at, lists.updated_at
FROM lists
INNER JOIN boards ON lists.board_id = boards.id
WHERE lists.id = $1 AND boards.user_id = $2
`

type GetUserListByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetUserListByID(ctx context.Context, arg GetUserListByIDParams) (List, error) {
	row := q.db.QueryRow(ctx, getUserListByID, arg.ID, arg.UserID)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BoardID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateList = `-- name: UpdateList :one
UPDATE lists
SET name = $1, position = $2, updated_at = now()
WHERE id = $3
RETURNING id, name, board_id, position, created_at, updated_at
`

type UpdateListParams struct {
	Name     string `json:"name"`
	Position int32  `json:"position"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList, arg.Name, arg.Position, arg.ID)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BoardID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
