// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserBoardByID(ctx context.Context, arg GetUserBoardByIDParams) (Board, error)
	GetUserBoards(ctx context.Context, userID string) ([]Board, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	RevokeRefreshToken(ctx context.Context, id string) (RefreshToken, error)
	UpdateUserBoardByID(ctx context.Context, arg UpdateUserBoardByIDParams) (Board, error)
}

var _ Querier = (*Queries)(nil)
