// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteList(ctx context.Context, id string) error
	DeleteUserBoardByID(ctx context.Context, arg DeleteUserBoardByIDParams) error
	GetBoardLists(ctx context.Context, boardID string) ([]List, error)
	GetList(ctx context.Context, id string) (List, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserBoardByID(ctx context.Context, arg GetUserBoardByIDParams) (Board, error)
	GetUserBoards(ctx context.Context, userID string) ([]Board, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	RevokeRefreshToken(ctx context.Context, id string) (RefreshToken, error)
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
	UpdateUserBoardByID(ctx context.Context, arg UpdateUserBoardByIDParams) (Board, error)
}

var _ Querier = (*Queries)(nil)
