basePath: /api/v1
definitions:
  apierrors.APIError:
    properties:
      code:
        type: string
      details:
        $ref: '#/definitions/apierrors.ErrorDetails'
      message:
        type: string
    type: object
  apierrors.ErrorDetails:
    additionalProperties:
      items:
        type: string
      type: array
    type: object
  apierrors.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/apierrors.APIError'
    type: object
  auth.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.SignInResponse:
    properties:
      access_token:
        type: string
    type: object
  auth.SignUpRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  auth.SignUpResponse:
    properties:
      email:
        type: string
    type: object
  boards.BoardResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  boards.CreateBoardRequest:
    properties:
      name:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - name
    type: object
  boards.ListBoardsResponse:
    properties:
      boards:
        items:
          $ref: '#/definitions/boards.BoardResponse'
        type: array
    type: object
  boards.SingleBoardResponse:
    properties:
      board:
        $ref: '#/definitions/boards.BoardResponse'
    type: object
  boards.UpdateBoardRequest:
    properties:
      name:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - name
    type: object
  cards.CardResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      list_id:
        type: string
      position:
        type: integer
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  cards.CreateCardRequest:
    properties:
      description:
        maxLength: 1000
        type: string
      position:
        minimum: 0
        type: integer
      status:
        enum:
        - todo
        - in_progress
        - done
        type: string
      title:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - position
    - status
    - title
    type: object
  cards.ListCardsResponse:
    properties:
      cards:
        items:
          $ref: '#/definitions/cards.CardResponse'
        type: array
    type: object
  cards.SingleCardResponse:
    properties:
      card:
        $ref: '#/definitions/cards.CardResponse'
    type: object
  cards.UpdateCardRequest:
    properties:
      description:
        maxLength: 1000
        type: string
      position:
        minimum: 0
        type: integer
      status:
        enum:
        - todo
        - in_progress
        - done
        type: string
      title:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - position
    - status
    - title
    type: object
  lists.CreateListRequest:
    properties:
      name:
        maxLength: 255
        minLength: 1
        type: string
      position:
        minimum: 0
        type: integer
    required:
    - name
    - position
    type: object
  lists.ListListsResponse:
    properties:
      lists:
        items:
          $ref: '#/definitions/lists.ListResponse'
        type: array
    type: object
  lists.ListResponse:
    properties:
      board_id:
        type: string
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      position:
        type: integer
      updated_at:
        type: string
    type: object
  lists.SingleListResponse:
    properties:
      list:
        $ref: '#/definitions/lists.ListResponse'
    type: object
  lists.UpdateListRequest:
    properties:
      name:
        maxLength: 255
        minLength: 1
        type: string
      position:
        minimum: 0
        type: integer
    required:
    - name
    - position
    type: object
host: localhost:3000
info:
  contact: {}
  description: REST API for a Trello-like app.
  title: TrellGo API
  version: "1.0"
paths:
  /auth/refresh:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.SignInResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      summary: Refresh access token
      tags:
      - auth
  /auth/signin:
    post:
      consumes:
      - application/json
      parameters:
      - description: Credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      summary: Sign in
      tags:
      - auth
  /auth/signout:
    delete:
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      summary: Sign out
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: Registration data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      summary: Sign up
      tags:
      - auth
  /boards:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/boards.ListBoardsResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List boards
      tags:
      - boards
    post:
      consumes:
      - application/json
      parameters:
      - description: Board data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/boards.CreateBoardRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/boards.SingleBoardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a board
      tags:
      - boards
  /boards/{board_id}/lists:
    get:
      parameters:
      - description: Board ID
        in: path
        name: board_id
        required: true
        type: string
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lists.ListListsResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List board lists
      tags:
      - lists
    post:
      consumes:
      - application/json
      parameters:
      - description: Board ID
        in: path
        name: board_id
        required: true
        type: string
      - description: List data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/lists.CreateListRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/lists.SingleListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a board list
      tags:
      - lists
  /boards/{id}:
    delete:
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete a board
      tags:
      - boards
    get:
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/boards.SingleBoardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a board
      tags:
      - boards
    patch:
      consumes:
      - application/json
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: string
      - description: Board data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/boards.UpdateBoardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/boards.SingleBoardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update a board
      tags:
      - boards
  /cards/{id}:
    delete:
      parameters:
      - description: Card ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete a card
      tags:
      - cards
    put:
      consumes:
      - application/json
      parameters:
      - description: Card ID
        in: path
        name: id
        required: true
        type: string
      - description: Card data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/cards.UpdateCardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cards.SingleCardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update a card
      tags:
      - cards
  /lists/{id}:
    delete:
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete a list
      tags:
      - lists
    patch:
      consumes:
      - application/json
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        type: string
      - description: List data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/lists.UpdateListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lists.SingleListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update a list
      tags:
      - lists
  /lists/{list_id}/cards:
    get:
      parameters:
      - description: List ID
        in: path
        name: list_id
        required: true
        type: string
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cards.ListCardsResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List cards of a list
      tags:
      - cards
    post:
      consumes:
      - application/json
      parameters:
      - description: List ID
        in: path
        name: list_id
        required: true
        type: string
      - description: Card data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/cards.CreateCardRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/cards.SingleCardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/apierrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a card in a list
      tags:
      - cards
securityDefinitions:
  BearerAuth:
    description: 'Enter: Bearer <token>'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
